CREATE TABLE IF NOT EXISTS `phone_numbers` (
	`id` VARCHAR(36) NOT NULL PRIMARY KEY,
    `number` VARCHAR(255) NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `created_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
