CREATE TABLE IF NOT EXISTS `book_authors` (
	`id` VARCHAR(36) NOT NULL PRIMARY KEY,
	`book_id` VARCHAR(36) NOT NULL,
	`person_id` VARCHAR(36) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

